"""Context Augmentor: Unified interface for context augmentation in LiTS.

Provides the ContextAugmentor ABC and ContextUnit dataclass that unify all
context augmentation mechanisms (critic, reflection, validation, profiling,
fact memory) under a single interface.

Method mapping from the old VerbalEvaluator:
    - evaluate()            -> analyze()           # paper: f_k(H_k)
    - (new)                 -> should_persist()     # paper: g(c) in {0,1}
    - _save_eval()          -> store()             # paper: M <- M U {c}
    - load_eval_as_prompt() -> retrieve()          # paper: C = U_k f_k(H_k)

Subclasses implement _analyze() returning a dict with 'issues' key.
The ABC wraps it into ContextUnit via the concrete analyze().
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional, Dict, Any, List, Union
from pathlib import Path
from datetime import datetime

from ...memory.types import normalize_trajectory_key

logger = logging.getLogger(__name__)


@dataclass
class ContextUnit:
    """Unified context data unit produced by ContextAugmentor.analyze().

    Paper correspondence: context unit c, generated by f_k(H_k).
    trajectory_key and query_id are required for retrieve-time
    history-access-based filtering.

    Args:
        content: Generated context (issue / critic / fact / reflection).
        source: Augmentor identifier ("critic", "validator", "profiler",
            "memory", "reflection").
        trajectory_key: Trajectory prefix identifier (e.g. "q/0/1/3"),
            used for cross-step filtering.
        query_id: Instance identifier, used for cross-trajectory filtering.
        metadata: Subclass-specific fields (error_type, timestamp, score).
    """
    content: str
    source: str
    trajectory_key: str
    query_id: int
    metadata: Dict[str, Any] = field(default_factory=dict)


class ContextAugmentor(ABC):
    """Unified context augmentation interface.

    All context augmentation mechanisms (critic, reflection, validation,
    profiling, fact memory) inherit from this ABC. Subclasses that follow
    the "call LLM, get dict with issues back" pattern implement _analyze();
    the ABC provides the concrete analyze() that wraps the dict into a
    ContextUnit.

    Subclasses that need a completely different analyze() flow (e.g.
    FactMemoryAugmentor) can override analyze() directly.

    Args:
        base_model: Optional LLM model. Required for LLM-based augmentors.
            None for non-LLM augmentors (FactMemoryAugmentor).
        persist: Controls persistence behaviour.
            True  -- always persist (default).
            False -- never persist.
            "auto" -- delegate to _should_persist_unit() hook.
        require_chat_model: If True, assert base_model is a chat model
            (HfChatModel, OpenAIChatModel, or BedrockChatModel).
            Used by LLM-based augmentors (SQLValidator, SQLErrorProfiler).
        temperature: Sampling temperature for LLM generation.
        max_new_tokens: Maximum tokens to generate.
        flush_threshold: Buffer size that triggers auto-flush to
            persistent storage. 0 (default) disables auto-flush,
            which is appropriate for non-buffering augmentors.
    """

    def __init__(
        self,
        base_model=None,
        persist: Union[bool, str] = True,
        require_chat_model: bool = False,
        temperature: float = 0.0,
        max_new_tokens: int = 500,
        flush_threshold: int = 0,
        **kwargs,
    ):
        if require_chat_model:
            from ...lm import HfChatModel, OpenAIChatModel
            from ...lm.bedrock_chat import BedrockChatModel

            assert isinstance(
                base_model, (HfChatModel, OpenAIChatModel, BedrockChatModel)
            ), f"base_model must be a chat model, got {type(base_model)}"

        self.base_model = base_model
        self.persist = persist  # True / False / "auto"
        self.temperature = temperature
        self.max_new_tokens = max_new_tokens
        self.flush_threshold = flush_threshold
        self._result_saver = None
        self._buffer: List[ContextUnit] = []
        self._policy_model_name: Optional[str] = None
        self._task_type: Optional[str] = None

        # Evaluator type identifier (used in stored records)
        # Respect subclass class-level override (e.g. CriticAugmentor.evaluator_type = "critic")
        if 'evaluator_type' not in type(self).__dict__:
            self.evaluator_type = self.__class__.__name__.lower()

        if base_model is not None:
            logger.info(
                f"Initialized {self.__class__.__name__} "
                f"with model: {base_model.__class__.__name__}"
            )
        else:
            logger.info(f"Initialized {self.__class__.__name__} (no base_model)")

    # ------------------------------------------------------------------
    # Storage context: set once, used by store() and flush_buffer()
    # ------------------------------------------------------------------

    def set_storage_context(
        self,
        policy_model_name: str,
        task_type: str,
    ) -> None:
        """Set storage parameters used by store() and flush_buffer().

        Called once by setup_augmentors() at search start. After this,
        store() and flush_buffer() no longer need these as kwargs.

        Args:
            policy_model_name: Model name for result file path.
            task_type: Task type for result file path.
        """
        self._policy_model_name = policy_model_name
        self._task_type = task_type

    # ------------------------------------------------------------------
    # Abstract: subclasses implement _analyze (was _evaluate)
    # ------------------------------------------------------------------

    def _analyze(self, *args, **kwargs) -> Optional[Dict[str, Any]]:
        """Subclass-specific analysis logic.

        Default raises NotImplementedError. Subclasses that use the
        dict-with-issues pattern implement this; subclasses that need
        a completely different flow override analyze() directly.

        Returns:
            Result dict (should contain 'issues' key), or None.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement _analyze() or "
            f"override analyze() directly."
        )

    # ------------------------------------------------------------------
    # LLM call helper (unified role for inference logging)
    # ------------------------------------------------------------------

    def _call_model(
        self,
        message: str,
        query_idx=None,
        from_phase: str = "",
        temperature: Optional[float] = None,
        max_new_tokens: Optional[int] = None,
        **kwargs,
    ):
        """Call self.base_model with a proper role for inference logging.

        Constructs role as ``augmentor_{query_idx}_{from_phase}`` so that
        InferenceLogger can attribute cost to this augmentor.

        Args:
            message: User message to send.
            query_idx: Example index (for logging).
            from_phase: Algorithm phase (for logging).
            temperature: Override self.temperature if given.
            max_new_tokens: Override self.max_new_tokens if given.

        Returns:
            LLM output object (has ``.text`` attribute).
        """
        from ..utils import create_role
        role = create_role("augmentor", query_idx, from_phase)
        return self.base_model(
            message,
            role=role,
            temperature=temperature if temperature is not None else self.temperature,
            max_new_tokens=max_new_tokens if max_new_tokens is not None else self.max_new_tokens,
            **kwargs,
        )

    # ------------------------------------------------------------------
    # Core pipeline: analyze -> should_persist -> store -> retrieve
    # ------------------------------------------------------------------

    def analyze(self, traj_state, **kwargs) -> Optional[ContextUnit]:
        """Analyze trajectory state and produce a context unit.

        Paper: f_k(H_k).

        Default implementation calls _analyze() and wraps the result dict
        into a ContextUnit. If the unit is non-None, it is appended to
        ``_buffer``. When ``flush_threshold > 0`` and the buffer reaches
        that size, ``flush_buffer()`` is called automatically.

        Subclasses implement ``_analyze()`` only; they should NOT override
        ``analyze()`` unless they need a completely different flow (e.g.
        FactMemoryAugmentor).
        """
        if hasattr(self, "sys_prompt") and self.base_model is not None:
            self.base_model.sys_prompt = self.sys_prompt

        result = self._analyze(traj_state, **kwargs)

        if result is None:
            return None

        issues = result.get("issues", [])
        if not issues:
            return None

        if isinstance(issues, str):
            content = issues
        elif isinstance(issues, list):
            content = "\n".join(str(i) for i in issues if i)
        else:
            content = str(issues)

        if not content:
            return None

        unit = ContextUnit(
            content=content,
            source=self.evaluator_type,
            trajectory_key=normalize_trajectory_key(kwargs.get("trajectory_key")),
            query_id=kwargs.get("query_idx", -1),
            metadata={k: v for k, v in result.items() if k != "issues"},
        )

        # Buffer accumulation + auto-flush (generic for all subclasses)
        self._buffer.append(unit)
        logger.debug(
            f"{self.__class__.__name__}: buffered unit "
            f"(buffer size: {len(self._buffer)})"
        )
        if self.flush_threshold > 0 and len(self._buffer) >= self.flush_threshold:
            self.flush_buffer()

        return unit

    def should_persist(self, unit: ContextUnit) -> bool:
        """Decide whether to persist a context unit.

        Paper: g(c) in {0, 1}.

        Controlled by self.persist:
            True  -- always persist (default).
            False -- never persist.
            "auto" -- delegate to _should_persist_unit() hook.
        """
        if self.persist is True:
            return True
        if self.persist is False:
            return False
        return self._should_persist_unit(unit)

    def _should_persist_unit(self, unit: ContextUnit) -> bool:
        """Subclass hook for persist='auto' mode. Default: False."""
        return False

    def store(self, unit: ContextUnit, **kwargs) -> None:
        """Persist a context unit. Paper: M <- M U {c | g(c)=1}.

        Default implementation writes to jsonl. Subclasses may override
        (e.g. FactMemoryAugmentor delegates to LiTSMemoryManager).

        Uses self._policy_model_name / self._task_type set by
        set_storage_context(). Falls back to kwargs for backward compat.
        """
        policy_model_name = self._policy_model_name or kwargs.get("policy_model_name")
        task_type = self._task_type or kwargs.get("task_type")
        if not policy_model_name or not task_type:
            logger.debug(
                "store() skipped: policy_model_name or task_type not provided"
            )
            return

        saver = self._get_result_saver(policy_model_name, task_type)
        record = {
            "evaluator_type": self.evaluator_type,
            "source": unit.source,
            "content": unit.content,
            "trajectory_key": unit.trajectory_key,
            "query_id": unit.query_id,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            **unit.metadata,
        }
        saver.append_result(record)
        logger.debug(f"Stored {self.evaluator_type} unit to {saver.filepath}")

    def retrieve(self, query_context=None, **kwargs) -> str:
        """Retrieve relevant context formatted as a prompt string.

        Paper: C = U_k f_k(H_k) injected into pi_theta(a | s, C).

        Default implementation delegates to load_eval_as_prompt for
        backward compat with the old VerbalEvaluator interface.
        Subclasses with different retrieval logic override this.
        """
        if query_context and isinstance(query_context, dict):
            pmn = query_context.get(
                "policy_model_name", kwargs.get("policy_model_name", "")
            )
            tt = query_context.get(
                "task_type", kwargs.get("task_type", "")
            )
        else:
            pmn = kwargs.get("policy_model_name", "")
            tt = kwargs.get("task_type", "")

        if not pmn or not tt:
            return ""

        return self.load_eval_as_prompt(pmn, tt, **kwargs)

    # ------------------------------------------------------------------
    # Backward-compatible convenience wrapper
    # ------------------------------------------------------------------

    def evaluate(self, *args, **kwargs) -> Optional[str]:
        """Convenience wrapper preserving the old VerbalEvaluator interface.

        Sets sys_prompt, calls _analyze, returns issues content or None.
        Existing ReAct learning-loop callers (step_evaluators /
        trajectory_evaluators) can keep calling evaluate() unchanged.
        """
        if hasattr(self, "sys_prompt") and self.base_model is not None:
            self.base_model.sys_prompt = self.sys_prompt

        result = self._analyze(*args, **kwargs)

        if result and result.get("issues"):
            return result["issues"]

        return None

    # ------------------------------------------------------------------
    # Retrieve helpers (Layer 1: history-access filter)
    # ------------------------------------------------------------------

    def _filter_by_history_access(
        self,
        history_access,
        trajectory_key: Optional[str],
        query_id: Optional[int],
        entries: Optional[List[ContextUnit]] = None,
    ) -> List[ContextUnit]:
        """Layer 1 filter: select entries by history access set.

        Filtering semantics per level:
            cross_step: trajectory_key == X AND query_id == Y
                (same step within the same task instance)
            cross_trajectory: query_id == Y
                (any trajectory within the same task instance)
            cross_task: no constraint (all entries)

        When query_id is None, cross_step degrades to trajectory_key
        match only (backward compat with callers that don't pass it).

        Args:
            history_access: Set of access levels, e.g.
                {"cross_step", "cross_trajectory"}.
            trajectory_key: Current trajectory prefix id.
            query_id: Current instance id.
            entries: Candidate entries. If None, uses self._buffer.

        Returns:
            De-duplicated list of matching ContextUnits.
        """
        if entries is None:
            entries = list(self._buffer)

        if not history_access:
            return entries

        seen_ids: set = set()
        candidates: List[ContextUnit] = []

        def _add(unit: ContextUnit):
            uid = id(unit)
            if uid not in seen_ids:
                seen_ids.add(uid)
                candidates.append(unit)

        for level in history_access:
            if level == "cross_step" and trajectory_key is not None:
                for u in entries:
                    if u.trajectory_key == trajectory_key and (
                        query_id is None or u.query_id == query_id
                    ):
                        _add(u)
            elif level == "cross_trajectory" and query_id is not None:
                for u in entries:
                    if u.query_id == query_id:
                        _add(u)
            elif level == "cross_task":
                for u in entries:
                    _add(u)

        return candidates

    def _rank_and_format(self, candidates: List[ContextUnit], query_context) -> str:
        """Layer 2: relevance ranking + prompt formatting.

        Default: join all candidate contents, most recent last.
        Subclasses override for custom ranking.
        """
        if not candidates:
            return ""
        return "\n".join(u.content for u in candidates)

    # ------------------------------------------------------------------
    # Write-back buffer infrastructure
    # ------------------------------------------------------------------

    def flush_buffer(self, **kwargs) -> None:
        """Flush buffered ContextUnits to persistent storage.

        Called at search end or when buffer exceeds a threshold.
        """
        for unit in self._buffer:
            self.store(unit, **kwargs)
        self._buffer.clear()
        logger.debug(f"{self.__class__.__name__}: flushed buffer")

    # ------------------------------------------------------------------
    # Result saver (jsonl) + legacy methods from VerbalEvaluator
    # ------------------------------------------------------------------

    def _get_result_saver(self, policy_model_name: str, task_type: str):
        """Get or create a ResultDictToJsonl saver for this policy/task pair.

        All augmentors for the same (policy_model_name, task_type) share
        one file. The evaluator_type field distinguishes records.

        Uses ~/.lits_llm/context_augmentor/ for persistent storage.
        """
        from ...eval.results import ResultDictToJsonl
        from ...lm import get_clean_model_name

        model_name_clean = get_clean_model_name(policy_model_name)
        run_id = f"{model_name_clean}_{task_type}"

        save_dir = Path.home() / ".lits_llm" / "context_augmentor"
        save_dir.mkdir(parents=True, exist_ok=True)

        filepath = str(save_dir / f"resultdicttojsonl_{run_id}.jsonl")

        if self._result_saver is None or self._result_saver.filepath != filepath:
            self._result_saver = ResultDictToJsonl(
                run_id=run_id,
                root_dir=str(save_dir),
                override=False,
            )
        return self._result_saver

    def load_results(
        self,
        policy_model_name: str,
        task_type: str,
        evaluator_type: Optional[str] = None,
    ) -> list:
        """Load saved results from disk.

        Args:
            policy_model_name: Policy model name.
            task_type: Task type.
            evaluator_type: Optional filter. If None, returns all records.
        """
        try:
            saver = self._get_result_saver(policy_model_name, task_type)
            if not saver.results:
                return []
            if evaluator_type:
                return [
                    r for r in saver.results
                    if r.get("evaluator_type") == evaluator_type
                ]
            return saver.results
        except Exception as e:
            logger.error(f"Error loading results: {e}")
            return []

    def _save_eval(
        self,
        result: Dict[str, Any],
        query_idx: Optional[int],
        policy_model_name: str,
        task_type: str,
    ) -> None:
        """Legacy save method -- kept for backward compat."""
        saver = self._get_result_saver(policy_model_name, task_type)
        record = {
            "evaluator_type": self.evaluator_type,
            "query_idx": query_idx,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            **result,
        }
        saver.append_result(record)
        logger.debug(f"Saved {self.evaluator_type} result to {saver.filepath}")

    def load_eval_as_prompt(
        self,
        policy_model_name: str,
        task_type: str,
        max_items: int = 10,
        include_all_evaluators: bool = False,
        **kwargs,
    ) -> str:
        """Load saved evaluations and format as prompt component.

        Issues are ranked by score (lower = worse = higher priority).

        Args:
            policy_model_name: Policy model name.
            task_type: Task type.
            max_items: Max individual issues to include.
            include_all_evaluators: If True, include all evaluator types.
        """
        try:
            all_results = self.load_results(policy_model_name, task_type)
            if not all_results:
                return ""

            results_by_type: Dict[str, list] = {}
            for result in all_results:
                eval_type = result.get("evaluator_type", "unknown")
                results_by_type.setdefault(eval_type, []).append(result)

            if include_all_evaluators:
                evaluator_types = list(results_by_type.keys())
            else:
                evaluator_types = [self.evaluator_type]

            prompt_parts: List[str] = []

            for eval_type in evaluator_types:
                if eval_type not in results_by_type:
                    continue

                results = results_by_type[eval_type]
                issue_items: List[Dict[str, Any]] = []
                for result in results:
                    issues = result.get("issues", [])
                    score = result.get("score")
                    error_type = result.get("error_type")
                    for issue in issues:
                        if issue:
                            issue_items.append({
                                "issue": issue,
                                "score": score if score is not None else float("inf"),
                                "error_type": error_type,
                            })

                if not issue_items:
                    continue

                issue_items.sort(key=lambda x: x["score"])
                top_issues = issue_items[:max_items]

                if eval_type == "sqlvalidator":
                    prompt_parts.append(
                        "**Avoid the following categories of SQL mistakes "
                        "that break geospatial semantics or CRS logic or "
                        "spatial reasoning principles:**\n"
                    )
                elif eval_type == "sqlerrorprofiler":
                    prompt_parts.append(
                        "**Avoid the following SQL errors arising from "
                        "incorrect use of schema elements:**\n"
                    )
                else:
                    prompt_parts.append("**Avoid the following issues:**\n")

                for item in top_issues:
                    issue = item["issue"]
                    et = item["error_type"]
                    if et:
                        prompt_parts.append(f"[* {et}] {issue}")
                    else:
                        prompt_parts.append(f"* {issue}")

                prompt_parts.append("")

            return "\n".join(prompt_parts).strip()

        except Exception as e:
            logger.error(f"Error loading evaluations as prompt: {e}")
            return ""


from .sql_validator import SQLValidator, extract_sql_from_action
from .sql_error_profiler import SQLErrorProfiler
from .critic import CriticAugmentor
from .reflection import ReflectionAugmentor
from .fact_memory import FactMemoryAugmentor

__all__ = [
    "ContextUnit",
    "ContextAugmentor",
    "CriticAugmentor",
    "ReflectionAugmentor",
    "FactMemoryAugmentor",
    "SQLValidator",
    "SQLErrorProfiler",
    "extract_sql_from_action",
]
